### ISSUE TITLE
sage:// protocol is no longer registered in Firefox 48.0

### ISSUE THREAD

**Issue by davidholtz** [petea/sage#147] opened 2016-08-16 02:04 UTC
![screen shot 2016-08-15 at 9 01 56 pm](https://cloud.githubusercontent.com/assets/1671333/17685678/e894e350-632b-11e6-9aa4-23c54c80f0c6.png)

**Comment by petea** [comment] 2016-08-16 05:05
Duplicate of #140

**Closed by petea** 2016-08-16 05:05 UTC
